<a href="https://colab.research.google.com/github/Ankur08kv/improved-octo-carnival/blob/main/assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x = float(input("Enter Basic Pay: "))
HRA = 0.1 * x
TA = HRA/2
s = x + HRA + TA
print("Salary={}".format(s))
if 80000<=x :
    print("High")
if 40000<=x<80000:
    print("moderate")
if 40000<x<=10000:
    print("Low")
if x<10000:
    print("Invalid")
  

Enter Basic Pay: 500000
Salary=575000.0
High


In [ ]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
Addition = a + b
Subtraction = a - b
Multiplication = a * b
Division = a / b
var = 1
while var!='0':

  print("Main Menu\n1) Addition\n2) Subtraction\n3) Multiplication\n4) Division")

  x = int(input("Enter choice: "))
  if x == 1:
     print("result is:",Addition)
  elif x == 2:
     print("result is:",Subtraction)
  elif x == 3:
     print("result is:",Multiplication)
  elif x == 4:
     print("result is:",Division)
  else:
     print('\nPlease enter a valid choice')
  var = (input('\nDo you want to Continue?(press 0 to stop)'))


Enter first number: 8
Enter second number: 4
Main Menu
1) Addition
2) Subtraction
3) Multiplication
4) Division
Enter choice: 1
result is: 12

Do you want to Continue?(press 0 to stop)1
Main Menu
1) Addition
2) Subtraction
3) Multiplication
4) Division
Enter choice: 2
result is: 4

Do you want to Continue?(press 0 to stop)1
Main Menu
1) Addition
2) Subtraction
3) Multiplication
4) Division
Enter choice: 3
result is: 32

Do you want to Continue?(press 0 to stop)1
Main Menu
1) Addition
2) Subtraction
3) Multiplication
4) Division
Enter choice: 4
result is: 2.0

Do you want to Continue?(press 0 to stop)0


In [3]:
import numpy as np
a = int(input("enter the no. of rows of matrix1:"))
b = int(input("enter the no. of columns of matrix1:"))
#use space between entries
print("Enter the matrix1 entries in single list:")
entries = list(map(int, input().split()))
matrix1 = np.array(entries).reshape(a,b)
print(matrix1)
m = int(input("enter the no. of rows of matrix2:"))
n = int(input("enter the no. of columns of matrix2:"))
#use space between entries
print("Enter the matrix2 entries in single list:")
entries = list(map(int, input().split()))
matrix2 = np.array(entries).reshape(a,b)
print(matrix2)
var =1
while var!='0':
    print('1.Add Matrices\n2.Multiply Matrices\n3.vertical concatenation\n4.horizontal concatenation\n5.Transpose Matrices\n6.Exit')
    choice = int(input('Enter Choice:'))
    if choice==1:
      print ("The addition of matrix is : ")
      print (np.add(matrix1,matrix2)) 
    elif choice==2:
      print ("The multiplication of matrix is : ") 
      print (np.dot(matrix1,matrix2))
    elif choice==3:
      print ("The vertical concatenation of matrix is : ") 
      print (np.vstack((matrix1,matrix2)))
    elif choice==4:
      print ("The horizontal concatenation of matrix is : ") 
      print (np.hstack((matrix1,matrix2)))
    elif choice==5:
      print ("The Transpose of matrix1 is : ") 
      print (matrix1.T) 
      print ("The Transpose of matrix2 is : ")
      print (matrix2.T)
    elif choice==6:
      exit(0)
    var = (input('\nDo you want to Continue?(press 0 to stop)'))

enter the no. of rows of matrix1:2
enter the no. of columns of matrix1:2
Enter the matrix1 entries in single list:
2 4 6 8
[[2 4]
 [6 8]]
enter the no. of rows of matrix2:2
enter the no. of columns of matrix2:2
Enter the matrix2 entries in single list:
1 3 7 9
[[1 3]
 [7 9]]
1.Add Matrices
2.Multiply Matrices
3.vertical concatenation
4.horizontal concatenation
5.Transpose Matrices
6.Exit
Enter Choice:4
The horizontal concatenation of matrix is : 
[[2 4 1 3]
 [6 8 7 9]]

Do you want to Continue?(press 0 to stop)0


In [ ]:
import re
x=1
while x != 0:
    s1 = input("Enter string: ")
    print(s1.swapcase())
    print(s1[::-1])
    all_freq = {}

    for i in s1:
        if i in all_freq:
            all_freq[i] += 1
        else:
            all_freq[i] = 1
    print("Count of all characters in {} is :\n ".format(s1)
          + str(all_freq))
    s2 = input("Enter sub string: ")
    if re.search(s2, s1):
        print("YES,sub string '{0}' is present in string '{1}' ".format(s2, s1))
    else:
        print("NO,sub string '{0}' is not present in string {1} ".format(s2, s1))
    x = int(input("Do you wish to continue? (Press 0 to stop)"))


Enter string: prabhat
PRABHAT
tahbarp
Count of all characters in prabhat is :
 {'p': 1, 'r': 1, 'a': 2, 'b': 1, 'h': 1, 't': 1}
Enter sub string: hat
YES,sub string 'hat' is present in string 'prabhat' 
Do you wish to continue? (Press 0 to stop)0
